### ISSUE TITLE
counter / projection

### ISSUE THREAD

**Issue by blinkinglight** [hallgren/eventsourcing#100] opened 2024-01-11 07:17 UTC
hey,
cant figure out, how to make new projection with other projection events.
lets say i have Account model+created/updated and i want to query Count +account model created events

**Comment by hallgrenx** [comment] 2024-01-11 07:47
Hello.

When you say projection do you mean a read model that is built from events from multiple aggregates?

BR Morgan

**Comment by blinkinglight** [comment] 2024-01-11 07:57
> Hello.
> 
> When you say projection do you mean a read model that is built from events from multiple aggregates?
> 
> BR Morgan

yes

**Comment by blinkinglight** [comment] 2024-01-11 09:01
also, i very like this idea https://github.com/modernice/goes/blob/main/examples/todo/events.go#L28 to map string to struct manually

**Comment by hallgrenx** [comment] 2024-01-11 12:31
> > Hello.
> > When you say projection do you mean a read model that is built from events from multiple aggregates?
> > BR Morgan
> 
> yes

There are two ways to subscribe to events from multiple aggregates.

1. Use the real time subscription from the repository.

```go
counter := 0
s2 := repo.Subscribers().All(func(e eventsourcing.Event) {
	switch e.Data().(type) {
	case *Event1, *Event2:
		counter++
	}
})
```

You can filter the events with the help of these functions.

All(f func(e Event)) *subscription
AggregateID(f func(e Event), aggregates ...aggregate) *subscription
Aggregate(f func(e Event), aggregates ...aggregate) *subscription
Event(f func(e Event), events ...interface{}) *subscription
Name(f func(e Event), aggregate string, events ...string) *subscription

2. If you wan't to build the projection on already stored event you currently need to get the events from the event store directly.
The sql event store has the `GlobalEvent` method that can be used to iterate alla events stored in the database. You will not get the event deserialised. https://github.com/hallgren/eventsourcing/blob/master/eventstore/sql/sql.go#L92

There is more to be done in this area.

**Comment by hallgrenx** [comment] 2024-01-11 12:34
> also, i very like this idea https://github.com/modernice/goes/blob/main/examples/todo/events.go#L28 to map string to struct manually

I have no experience from this repo. What is this used for? Register event in the "goes" framework?

**Comment by blinkinglight** [comment] 2024-01-11 12:44
> > also, i very like this idea https://github.com/modernice/goes/blob/main/examples/todo/events.go#L28 to map string to struct manually
> 
> I have no experience from this repo. What is this used for? Register event in the "goes" framework?

yes, and i think in your framework its called "reason"

**Comment by hallgrenx** [comment] 2024-01-11 12:53
> > > also, i very like this idea https://github.com/modernice/goes/blob/main/examples/todo/events.go#L28 to map string to struct manually
> > 
> > 
> > I have no experience from this repo. What is this used for? Register event in the "goes" framework?
> 
> yes, and i think in your framework its called "reason"

https://github.com/hallgren/eventsourcing/blob/master/event.go#L39

```go
func (e Event) Reason() string {
	if e.data == nil {
		return ""
	}
	return reflect.TypeOf(e.data).Elem().Name()
}
```
And the reason "string" is based on the underlaying event type.

**Comment by blinkinglight** [comment] 2024-01-11 15:20
just an idea: 
https://github.com/blinkinglight/eventsourcing/blob/mod1/aggregateroot.go#L156
you can check in branch example

**Comment by hallgrenx** [comment] 2024-01-11 15:41
Why would you split the event reason out from the event? Isn't there a risk of tracking the same event but using different "reasons" if the reason is separated from the event?

```go
func (ar *AggregateRoot) TrackChange(a aggregate, event string, data interface{}) {

before:
func (ar *AggregateRoot) TrackChange(a aggregate, data interface{}) {

```

**Comment by blinkinglight** [comment] 2024-01-11 15:50
> Why would you split the event reason out from the event? Isn't there a risk of tracking the same event but using different "reasons" if the reason is separated from the event?
> 
> ```go
> func (ar *AggregateRoot) TrackChange(a aggregate, event string, data interface{}) {
> 
> before:
> func (ar *AggregateRoot) TrackChange(a aggregate, data interface{}) {
> ```

sorry for confusion, i just experimenting with this.

**Comment by blinkinglight** [comment] 2024-01-11 16:28
p.s. : 

> Projections are a necessary part of any event sourced or CQRS system. These systems don't rely on a single generic data source such as a normalised MySQL database. Instead you build up your data sets by playing through the events, i.e the “film”, "projecting" them into the shape you want.

so projection should read any events of any aggregate. because you constructing  / reconstructing state from "past" events ( lets say how much created events created in period of time also could be projection (analytics))

**Comment by hallgrenx** [comment] 2024-01-11 18:06
> > Why would you split the event reason out from the event?
> 
> what if... i made wrong name for struct or not in english, if i want to change it i need to update db ?

An event is immutable you should create a new event.

**Comment by hallgrenx** [comment] 2024-01-11 18:13
> p.s. :
> 
> > Projections are a necessary part of any event sourced or CQRS system. These systems don't rely on a single generic data source such as a normalised MySQL database. Instead you build up your data sets by playing through the events, i.e the “film”, "projecting" them into the shape you want.
> 
> so projection should read any events of any aggregate. because you constructing / reconstructing state from "past" events ( lets say how much created events created in period of time also could be projection (analytics))

I agree that a system based on event sourcing often need views that is built upon different aggregate events. Does it have to be part of this project? I don't know. It's pretty straight forward iterating all events from the event store and produce a projection. My main focus with this project is the write side and how to model events and aggregates.

**Comment by blinkinglight** [comment] 2024-01-15 10:21
> I have been thinking about this during the weekend and I will give projections a go. I will do event store specific methods that return the same iterator interface used when building the aggregate in the event repository. The events in the iterator is not tied to the aggregate but instead depend on the exposed method on the event store.
> 
> ex: All(start, cound uint64) (iterator, error) <- will return an iterator with global events based on a start position in the global event stream.

somethign like "replay and subscribe" ? 

> 
> Dependent on the event store its possible to filter the event, ex sql has more possibilities than the memory based event store.
i think with something like Options pattern ( WithName(name) , WithDateRange(from,to)) you can implement in any event store same queries (basically where aggregate name, event name, created at < > needs to be queries by default ) 
> 
> @blinkinglight would this fit your needs?

hope so :)

**Comment by hallgren** [comment] 2024-01-16 12:44
> > I have been thinking about this during the weekend and I will give projections a go. I will do event store specific methods that return the same iterator interface used when building the aggregate in the event repository. The events in the iterator is not tied to the aggregate but instead depend on the exposed method on the event store.
> > ex: All(start, cound uint64) (iterator, error) <- will return an iterator with global events based on a start position in the global event stream.
> 
> something like "replay and subscribe" ?

Would you like to combine replay and subscribe. First replay old events and when done start subscribe to events in "realtime"?

> 
> > Dependent on the event store its possible to filter the event, ex sql has more possibilities than the memory based event store.
> 
> i think with something like Options pattern ( WithName(name) , WithDateRange(from,to)) you can implement in any event store same queries (basically where aggregate name, event name, created at < > needs to be queries by default )
> 
> > @blinkinglight would this fit your needs?
> 
> hope so :)

The problem is that not all event stores have indexed events and should have to iterate all events to support queries like that.

**Comment by hallgrenx** [comment] 2024-02-08 07:32
@blinkinglight The projections PR is starting to take form. Do you have any feedback on the API design?

**Comment by hallgren** [comment] 2024-02-14 18:09
@blinkinglight I close this issue as projections are on it's way.

**Closed by hallgren** 2024-02-14 18:09 UTC
